default: &default
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000
  database: sw_dev

development:
  <<: *default

test:
  <<: *default
  database: sw_test

production:
  <<: *default
  database: sw
